site_name: Multipurpose Macro Load Bearing Assistive Follower Robot
site_url:  https://ras598-2025-s-team07.github.io
repo_url:  https://github.com/RAS598-2025-S-Team07/RAS598-2025-S-Team07.github.io
edit_uri:  edit/main/docs/

theme:
  name: material
  palette:
    primary: blue
    accent: indigo
nav:
  - Home: index.md 


